### PR TITLE
feat: automatically adjust GOMAXPROCS based on the CPU quota

### PR DESCRIPTION
**Pull request by shanduur**
## What this PR does / why we need it:

This PR introduces `go.uber.org/automaxprocs`, a library automatically adjusting `GOMAXPROCS` based on Linux container CPU quota. It eliminates manual configuration, optimizes performance, and prevents throttling, simplifying containerized Go application management.

## Which issue(s) this PR resolves:

N/A

## Special notes for your reviewer:

N/A

## Additional documentation e.g., enhancement proposals, usage docs, etc.:

N/A

### CODE REVIEW

**Comment by avestuk** [comment]
You might want a note about using integer CPU requests

**Comment by shanduur** [comment]
> You might want a note about using integer CPU requests

IMHO, it works as expected. Or do you mean documentation note?

---

1. With non integer CPU limits:

   When defining the following resources:
   ```yaml
   resources:
     limits:
       cpu: 1999m
   ```

   The `GOMAXPROCS` will be set to 1, as the rounding function always does the _floor_ operation.

2. If we leave the limits unset, and just set the requests, as follows:
   ```yaml
   resources:
     requests:
       cpu: 100m
   ```

   The `GOMAXPROCS` will be set to the number of CPU cores on the node, as the _cgroups_ only specify the limit, not the request.

**Comment by avestuk** [comment]
>     1. With non integer CPU limits:
>        When defining the following resources:
>        ```yaml
>        resources:
>          limits:
>            cpu: 1999m
>        ```        
>          
>        The `GOMAXPROCS` will be set to 1, as the rounding function always does the _floor_ operation.

Yes I mean this first case. I'd add a note somewhere describing this behaviour.

**Comment by shanduur** [comment]
@avestuk added note to Helm values.

**Review by avestuk — APPROVED** [review]

**Pull request merged**
